name: Compile Sketch

on:
  - push
  - pull_request

jobs:
  compile-sketche:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          arduino-version: latest
          board: arduino:avr:uno
      - name: Compile sketche
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno
          sketch-paths: |
            ./
          libraries: |
            - name: ArtNet
            - name: Ethernet
